### PR TITLE
Go to definition

### PR DESCRIPTION
**Pull request by RobinTournemenne**
Hello, 

here is a first proposition for the peek and go to definition feature that I missed too much from the matlab native ide.

It works well for different files but doesn't work for nested functions. I tried my best, but since I don't know how to create Promise I could not add this feature.

It is almost a direct copy from the vue peek extension.

Best regards!

Robin

### CODE REVIEW

**Comment by RobinTournemenne** [comment]
I finally implemented nested function behavior thanks to a javascript professionnal!

**Comment by Gimly** [comment]
Hi @RobinTournemenne, I'm really sorry to not have answered earlier as I'm quite busy at the moment. I've took a quick look and it looks pretty nice, thanks a lot. I'll try to do a more in depth review soon and I'll merge and deploy a new version.

**Comment by RobinTournemenne** [comment]
No problem, I do these propositions more for the community than for myself, given that I can add directly my features replacing brutaly the /out using the vsce command.

I am now considering doing the same for references which would be awesome since this feature is sadly lacking from the matlab native IDE! 

I always craved for it: "Imagine an IDE where you can see every occurence of a variable in a user friendly manner..." This dream may come true.

**Comment by RobinTournemenne** [comment]
By the way, if you add this feature to the matlab extension, I think it would nice to mention the "contribution" of the vue peek extension author:
 
https://github.com/fuzinato/vscode-vue-peek

In any case, he didn't licence his extension so we technically can do anything with it.

**Comment by RobinTournemenne** [comment]
I corrected a trivial mistake (I didn't think about the case when nested functions return values)

**Comment by kaungsgit** [comment]
Hi @Gimly and @RobinTournemenne , I have a quick question on why this doesn't work on methods. For example, hde_dig is an instance of an object and correct_hde is a method underneath. "Go to definition" works well with variables, and classes and I really appreciate you guys for improving this archaic MATLAB editor.

image

**Pull request merged**
