### PR TITLE
Update `vscode-textmate-languageservice` from 0.1.1 to 0.2.0

### LINKED ISSUE #140: can't use linter in 2.20

### LINKED ISSUE #141: Outline says No Symbols Found in document 'xxx.m' with v.2.2.0
Hi Xavier,

Firstly, I like to thank you for providing such a nice program.

I found that Outline says 'No Symbols Found f]in document 'xxx.m'' with v.2.2.0.
By downgrading to v2.0.1, the issue is gone.

I am glad if you can check this issue.

Thank you again,
Kosuke

### LINKED ISSUE #142: 2.2.0 freezing VS code on large files
Hi Gimly,

sorry to tell you that this interesting 2.2.0 update seems to freeze VS Code on a large matlab file (during colorization I guess): 689 lines defining one structure containing notably large cell arrays (~20 cells usually) with matrix inside (usually 2x20).

I cannot provide you with this confidential file, but maybe if you really need it, I can create an identical fac simile.

Best regards,

Robin

PS: I switched back to 2.0.1 which scans files 10 times faster

### LINKED ISSUE #143: ctrl+click to open function not working in 2.2.0
Hi, thanks for the update, the improved grammar works quite nicely. 
However, with the update, the ability to ctrl+click a function name to open that function if its in the same project broke. 

This was very convenient. For now I am reverting to 2.0.1.

### LINKED ISSUE #145: Snippets and Code Checking is not working with MATLAB 2021B
I'm, currently using Matlab 2021b version, and  Snippets and Code Checking are not working.
Did anyone how know how to fix this?

I'm also attaching my setting.
Capture

### LINKED ISSUE #147: Go to definition  is not working
this feature just works for 2.0.0 and 2.0.1 not furthermore!
2.2.0 has no "Go to definition" feature
2.2.1 has it, but not working
seems something has been rollbacked!

### PR DESCRIPTION
**Pull request by SNDST00M**
Closes #140, closes #141, closes #142, closes #143, closes #145, closes #147.

Changelog:

- Update grammar with extended function definition syntax and superclass method `@` operator.
- Update Textmate service API with optimisations, bugfixes and Atom's Textmate scope parser.

Tasks:

  - [x] Cannot use linter - #140.
  - [x] Cannot use "Peek Definition" - #140.
  - [x] "No symbols found" in Outline pane - #141.
  - [x] Freezes and remains uneditable on opening a large file - #142.
  - [x] ~~Slowdown on large files~~ - #142. (stretch goal 💪🏾, shelved in this release)
  - [x] CTRL-Click to open function definition does not work - #143. 
  - [x] Snippets and Code Checking is not working - #145.
  - [x] Go to Definition is not working - #146. (duplicate)

N.B: Major change - `meta.parens` does not match `meta.function-call.parens` in Textmate scope selectors.

### CODE REVIEW

**Comment by SNDST00M** [comment]
List of problems to fix:

- #140:
  - [x] Cannot use linter.
  - [x] Cannot use "Peek Definition".
- #141
  - [x] "No symbols found" in Outline pane.
- #142
  - [x] Freezes and remains uneditable on opening a large file.
  - [ ] Slowdown on large files - stretch goal. 💪🏾
- #143
  - [x] CTRL-Click to open function definition does not work.
- #145
  - [x] Snippets and Code Checking is not working.
- #146
  - [x] Go to Definition is not working. (duplicate)

**Comment by SNDST00M** [comment]
@Gimly could this go out before New Year?

**Comment by Gimly** [comment]
Could you please update the CHANGELOG.md at the root of the repository with the changes you did?

I'll then merge and try to push a new version today.

**Comment by SNDST00M** [comment]
Done, is esbuild okay now that we have no WASM and native dependencies?

**Comment by Gimly** [comment]
I think it should, but haven't had the time to do further testing, we'll see how it goes.

**Comment by SNDST00M** [comment]
#151 should be good for release in 1.3.0 also. Will research making this run in the browser too :)

**Pull request merged**
