### PR TITLE
Bump vscode-textmate-languageservice from 0.2.1 to 1.1.0

### LINKED ISSUE #143: ctrl+click to open function not working in 2.2.0
Hi, thanks for the update, the improved grammar works quite nicely. 
However, with the update, the ability to ctrl+click a function name to open that function if its in the same project broke. 

This was very convenient. For now I am reverting to 2.0.1.

### LINKED ISSUE #147: Go to definition  is not working
this feature just works for 2.0.0 and 2.0.1 not furthermore!
2.2.0 has no "Go to definition" feature
2.2.1 has it, but not working
seems something has been rollbacked!

### LINKED ISSUE #152: Extension v2.3.0 becomes unresponsive
```
[2021-12-15 13:06:33.799] [renderer8] [warning] UNRESPONSIVE extension host, 'Gimly81.matlab' took 98% of 3079.676ms, saved PROFILE here: 'file:///var/folders/vt/l5v0pvrx21s0r239h0zylz2r0000gn/T/exthost-8a6262.cpuprofile' 
[2021-12-15 13:07:13.004] [renderer8] [warning] UNRESPONSIVE extension host, 'Gimly81.matlab' took 63% of 7642.598ms, saved PROFILE here: 'file:///var/folders/vt/l5v0pvrx21s0r239h0zylz2r0000gn/T/exthost-4b14e9.cpuprofile' 
```

Here is the cpu profile: 
[exthost-8a6262.cpuprofile.zip](https://github.com/Gimly/vscode-matlab/files/7719219/exthost-8a6262.cpuprofile.zip)

This did not occur until a few days ago, so I suspect a recent change, which could be v2.3.0.

### LINKED ISSUE #157: Performance issues with folding
Using VSCode 1.63.3, MATLAB 2021b on macOS 12.1 I am having many performance problems. I have disabled all my extensions except this one. I have `lintOnSave` set to `false`, and have tried providing or commenting out the mlint path. Every time I save the Process Explorer shows extension host go up to 100% CPU and saving takes a couple of seconds for a MATLAB classdef ~1500 lines log. It is as if lint on save is still activated? General performance slows down too with extension host often hitting 100%. Disabling the extension and everything goes back to normal... Is there a way to fully disable linting?

### LINKED ISSUE #159: if, else, end one liners disrupt the outline
Hello,
```
function printNice(param)
    if param; disp('true'); else; disp('false'); end
    cmd = '@echo nice';
    dos(cmd);
end
```
produces a wrong outline:
image

else and cmd are shown outside the function.

Regards,
Simon

### LINKED ISSUE #162: Lag typing large file with Matlab extention
Issue Type: <b>Performance Issue</b>

On large matlab files >800 lines,
I have several seconds of lag when typing a letter or even when I hit the arrow to move inside the code. Suprisingly backspace or ctrl+z works intantly. I do not have this latency when disable matlab extention but also my emacs extension. Could it be a compatibility issue ?

Extension version: 2.3.1
VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Fetching remote diagnostics for 'ssh-remote+7b22686f73744e616d65223a22746c6c69663230222c2275736572223a226a61637175657031227d' timed out.
Remote OS version: Linux x64 3.10.0-693.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (6.78GB free)|
|Process Argv|--crash-reporter-id 45a3798f-1e4c-4fd3-aa26-0d04032a23df|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+7b22686f73744e616d65223a22746c6c69663230222c2275736572223a226a61637175657031227d' timed out.

|Item|Value|
|---|---|
|Remote|SSH: tllif20|
|OS|Linux x64 3.10.0-693.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz (24 x 3000)|
|Memory (System)|376.40GB (313.87GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    96	 18616	code main
    0	    65	  1756	   shared-process
    0	    37	 14076	     ptyHost
    0	     6	 13240	       C:\WINDOWS\System32\cmd.exe /c (type "C:\Users\jacquep1\AppData\Local\Temp\vscode-linux-multi-line-command-tllif20-406830708.sh" | ssh -T -D 56084 "jacquep1@tllif20" bash) & exit /b 0
    0	     8	  6512	         ssh  -T -D 56084 "jacquep1@tllif20" bash
    0	     5	 13816	       console-window-host (Windows internal process)
    0	     5	 17256	       C:\WINDOWS\System32\cmd.exe /c (type "C:\Users\jacquep1\AppData\Local\Temp\vscode-linux-multi-line-command-tllif20-319232353.sh" | ssh -T -D 59838 "jacquep1@tllif20" bash) & exit /b 0
    0	     7	 11212	         ssh  -T -D 59838 "jacquep1@tllif20" bash
    0	     5	 22136	       console-window-host (Windows internal process)
    0	     9	  6544	   crashpad-handler
    1	    53	  7672	   window (Issue Reporter)
    0	   128	  8372	   window (job_shop.m - test [SSH: tllif20] - Visual Studio Code)
    0	    35	 14896	     extensionHost
    0	    25	 11040	   utility
    0	    16	 12080	   utility
    0	   180	 13808	   gpu-process
    0	   186	 22232	   window (gurobi_model_oneband_allts.m - 52_idem49_seuilincline245 [SSH: tllif20] - Visual Studio Code)
    0	    59	  7420	     extensionHost
Fetching remote diagnostics for 'ssh-remote+7b22686f73744e616d65223a22746c6c69663230222c2275736572223a226a61637175657031227d' timed out.

Remote: SSH: tllif20
```

</details>
<details>
<summary>Workspace Info</summary>

```

Fetching remote diagnostics for 'ssh-remote+7b22686f73744e616d65223a22746c6c69663230222c2275736572223a226a61637175657031227d' timed out.;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30429732
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscgsvidc:30447482
vscaat:30438848
pynewfile477cf:30450039

```

</details>

### LINKED ISSUE #165: This extension keeps crashing the Extension Host
Even if this is the only active extension it keeps crashing the host. 
VSC 1.68.1
Extension version v2.3.1. Tried regressing to older versions but same thing happens. 

INFO UNRESPONSIVE extension host: starting to profile NOW
WARN UNRESPONSIVE extension host: 'Gimly81.matlab' took 65% of 5242.499ms
Extension host (LocalProcess) terminated unexpectedly. Code: 134, Signal: null

This prevents the Search results updating until host is restarted. Happens frequently but not immediately.

Happens on Windows or Linux.

No linter or matlab paths defined.

### LINKED ISSUE #168: Extension Host Terminated unexpectedly
Matlab extension will cause extension host to terminate unexpectedly

### LINKED ISSUE #172: Extremely slow: Go to Definition F12 or Peek Definition
Dear Hahn Xavier,
first of all thank you for the great work and for sharing with all of us. I find myself quite often right-clicking and choosing "Go to Definition". However, it takes several seconds for this operation to complete although Control-Find the name of the function works like a charm. Is it a performance problem, wrong implementation or what? You have the list of functions from the top up menu, so why does this terrible slow down happen? Peek definition is also quite slow. It seems you are trying to create the list of function first although you already have them in the top {} methods > menu.

Additionally quite useful would be (if is it possible to implement that) the "Find all References" of a member method or variable. 

Thank you for the great work, and all best wishes.

### PR DESCRIPTION
**Pull request by ghost**
This is a full rewrite of the library that kills all tech debt, perf issues, and also **adds browser support**.

All providers exit within 100ms except for the definition provider which takes 1200ms. Not perfect but we've cut overheads by 1-2 orders of magnitude!
3 running theories for improvements.. mainly putting a stack variable for variable-property text merging in the tokenizer, & coalescing output data further to kill any overhead.

Not sure we are at the finish line here, but this will close a bunch of issues for sure.

These issues had regression test cases built to test them.. definitely killed these bugs 😄

- Closes #157.
- Closes #159.
- Closes #162.
- Closes #165.
- Closes #168.
- Closes #172.
- Fixes #147.
- Fixes #143.
- Fixes #152.

If the changelogs interest you... [`1.0.0-rc-1`](https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/blob/main/CHANGELOG.md#100-rc-1) and [`1.0.0-rc-2`](https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/blob/main/CHANGELOG.md#100-rc-2)

### CODE REVIEW

**Comment by M00TSDNS** [comment]
If the changelings interest you... [`1.0.0-rc-1`](https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/blob/main/CHANGELOG.md#100-rc-1) and [`1.0.0-rc-2`](https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/blob/main/CHANGELOG.md#100-rc-2)

**Comment by M00TSDNS** [comment]
Testing: fully tested on my local machine, and via `npm test` against the [library's test suite](https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/tree/v1.0.0-rc-2/test/suite).

**Comment by jankap** [comment]
This is awesome! Big question: will @Gimly merge this or not in the future? Can I try this out on my PC already?

**Comment by M00TSDNS** [comment]
Run it in PWSH for Windows or your bash console on Unix:

```
cd ~/.vscode/extensions/gimly81.matlab-2.*
npm i vscode-textmate-languageservice@1.0.0
```

**Comment by M00TSDNS** [comment]
Shoot... you will have to clone this out, `npx vsce package` then install the VSIX file.

**Comment by jiecui** [comment]
Huge thanks!!

**Comment by M00TSDNS** [comment]
Did you upgrade via `npm i`? There are some changes to the way the LSP is initialised.. hopefully for the last time but yeah

**Comment by M00TSDNS** [comment]
Put all these commands in the console @jiecui:

```console
$ cd ..
$ git clone https://github.com/M00TSDNS/vscode-matlab.git
$ cd vscode-matlab
$ git checkout hotfix-lsp-perfs
$ vsce package
$ code --install-extension matlab-2.3.1.vsix
```

Then refresh the window @jiecui

**Comment by jiecui** [comment]
Sorry for the late reply.  Thanks a lot for the comments! 
All the above commands were executed successfully, but mlint problem persisted. In addition, the editor also lost colorization of some of the code.  I switched to Matlab extension older version v2.0.0, which works all right.

**Comment by M00TSDNS** [comment]
I am downloading a fresh purchased copy of Matlab to debug today

**Comment by M00TSDNS** [comment]
Works for me:

image

**Comment by jiecui** [comment]
Thanks! Probably, the issue is at my end. How can I remove Xavier Hahn's Matlab extension completely and try a fresh start?

**Comment by M00TSDNS** [comment]
`code --install-extension matlab-2.3.1.vsix` should have done it 🤔

**Comment by jiecui** [comment]
Still doesn't work well for me after a complete re-installation, but I guess the issue should be at my end.  Thanks anyway!

image

**Comment by M00TSDNS** [comment]
We now have web support! Better than Anycode 🎁❣

**Comment by M00TSDNS** [comment]
@jiecui go to [github.dev/jiecui/mpact](https://github.dev/jiecui/mpact) - please install `[EXPERIMENTAL] Matlab` extension and try it.

**Comment by jiecui** [comment]
Nice!

**Comment by eluum** [comment]
I have not been able to get this working for vscode on windows, seems like I have the same issue as @jiecui based on his screenshot. Building and installing the package from the cloned repo doesn't seem to work, using the version in the vscode extension Marketplace works but lags too much to be usable.

**Comment by M00TSDNS** [comment]
Riiight.. you've got to do `git submodule update --init` to have the grammar.

@Gimly you'll need to do `npm i npm-run-all --save-dev` and commit the new dependency to fix the build..

**Comment by eluum** [comment]
Thanks, everything is working now. Great job making this extension usable!

**Pull request merged**
