### PR TITLE
Add dynamic language providers

### PR DESCRIPTION
**Pull request by SNDST00M**
Adds the following providers:

- Table of Contents / outline provider
- Document symbol provider for all entity symbols
- Folding provider
- Peek definition provider for all entity symbols
- Workspace symbol provider

### CODE REVIEW

**Comment by SNDST00M** [comment]
@Gimly just need to resolve conflicts then this will be ready to ship! 🎉

**Comment by SNDST00M** [comment]
Actually I'm going to be folding readwrite variable injections into the upstream grammar.
The pull should be mergeable after that.

**Comment by SNDST00M** [comment]
@Gimly This is ready to ship 🚀🚀🚀

**Comment by Gimly** [comment]
@SNDST00M  There seems to be some merge conflicts, can you please fix them before I can merge?

**Comment by SNDST00M** [comment]
I don't see any now - "This branch has no conflicts with the base branch"

**Comment by SNDST00M** [comment]
```console
$ git merge upstream/master
Already up to date.
```

**Comment by Gimly** [comment]
OK, weird, it's GitHub behaving weirdly. It looks OK now.

**Comment by Gimly** [comment]
Merged ! Thanks !

**Comment by SNDST00M** [comment]
No problem! Hopefully this can ship to the marketplace in October

**Comment by Gimly** [comment]
@SNDST00M I've tried to publish a version yesterday but I had some issues with NPM. I'll try to work on it this evening.

**Comment by Gimly** [comment]
@SNDST00M just published the latest version. Thanks for your great work !

**Pull request merged**
